name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pull-request-title:
    uses: cccteam/github-workflows/.github/workflows/semantic-pull-request-title.yml@v5.20.1

  golang-ci:
    uses: cccteam/github-workflows/.github/workflows/golang-ci.yml@v5.20.1
    with:
      build-tags: '["", "dev,skipAuth"]'
      golangci-lint-version: 'v2.7.2'
