name: Security Scan

on:
  schedule:
    - cron: "0 14 * * 1" # Monday at 8:00 AM CDT
  workflow_dispatch:

jobs:
  security_scan:
    uses: cccteam/github-workflows/.github/workflows/golang-security-scan.yml@v5.18.1
    with:
      execute-trivy-scan: false
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.CCC_SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      DEPENDABOT_ALERTS_TOKEN: ${{ secrets.DEPENDABOT_ALERTS_TOKEN }}